### ISSUE TITLE
Unit Model creation

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#15]
Currently all our units are cubes with numbers. With the addition from the changed requirements, that will not suffice. From the #1 meeting we have vaguely drafted the following sample ideas for the two units

---
**EDIT:** the unit designs discussed below are now left as a backup, for more information refer to [this comment](https://github.com/Nicodaw/Uni-UniversityDominationA4/issues/15#issuecomment-373940976)

---
Undergrad
Reuse our original model from assessment 2 for the "plain dude". Shirt signifies the colour of the player a unit belongs to and a sign above the units head always shows the level.

Postgrad
Similar, but put a graduation cap on the unit

![](https://puu.sh/zxyVM/2cacee6ca7.png)

**Comment by Nicodaw** [comment]
I find several issues with the units being represented like this:

1. Not sure how the pixel style will fit (although the buildings are pretty much blocks, so it's not that big of an issue)
2. In the current suggestion, they will stand far too tall; Possible fix: squish the model so that model + sign are about as tall as the model pre-squishing
3. Is the graduation cap enough to differentiate between an undergrad and a post-grad ?

**Comment by Gorea235** [comment]
I think the size might be a slight issue, especially with the way the map works (we need large numbers for it to be clear). This would also affect the difference with the hats, since to make the units fit we might have to have them smaller than we would like. We could move the number to their chest and display it like that? It would mean that the unit could be a little bigger & clearer. If the hat is not clear enough, then we could add arms to improve distinction.

This also feeds into another issue, which is clarity of the effects. Effects that are applied to sectors, players or units need to be shown to the user in a way that is clear and distinct enough to be playable.

**Comment by Nicodaw** [comment]
Previously discussed reuse of the old unit from game one has been left as a backup, because a more fitting model for the game style can be created. The needed features are:

- Model should be short so it does not obstruct other sectors, but still clearly distinguishable
- Have a clear indication of level and owner (i.e. the "torso" having a number for the level and being coloured with the player's colour). So similar to previous times: the 3D object has to have a single child element (i.e. the torso), which will be changed via code.
- Postgrad and undergrad units clearly distinguishable
- **NEW**: Display the unit specific attack and defence (probably a small floating banner [⚔️ n   🛡️ n] or something else that fits the style and is small, yet readable). The actual contents of the banner are most likely to be done in the Unity editor, but the style of it should be designed separately.

It's important that units are 3D and not just sprites. Probably the easiest way I can think of a way to incorporate a more intricate design is to draw it as a sprite and put it on a 3D object as its texture. This is only a prima vista so there may be better ways to do it.

**Comment by Gorea235** [comment]
The new models were implemented a while ago, so unless there is any more changes we need to do, I will close this issue.
