### ISSUE TITLE
Unit implementation change

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#18]
**Note:** This issue is currently undergoing discussion as the features of the postgrad are dependent on the features in the card system #17

Undergrad
-

_1. Acquiring:_
At start of every turn, spawn an undergrad at a Landmark you control (if landmark is unoccupied)

_2. Movement Range:_
Only on adjacent sectors

_3. Level cap:_
max level 5
 

Postgrad
-

_1. Acquiring:_
>**TBD**

_2. Movement Range:_
>**TBD**

_3. Level cap:_
 >**TBD**

**Comment by Gorea235** [comment]
The postgrad upgrade and effects will all be dealt with by the card system (#17), and #7 will be where we actually implement the details for how the effect system will work.

**Comment by Gorea235** [comment]
The units were reworked in 7c8f65e, so all that is left is to finish them up ready for the effect system. We need to move the highlighting system to a range-based one, which will likely need to use a flood-fill algorithm to get all the sectors in range.

The actual range values are in `Unit`, however it might be good to implement the actual highlighter in `Sector` and have a wrapping in `Unit` that calls it.  Also, we should implement a system for un-highlighting all sectors so we can properly handle it (this would be done in `Map`).

Side note, we need to modify `Player` to also have highlighting as well, since we need to use it for the effect selection highlighting.

**Comment by Gorea235** [comment]
The postgrad effect is implemented, and is working. The range-based highlighting has it's own issue (#25), so this issue is now done.
