### ISSUE TITLE
Rework PVC allocation

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#2]
Current implementation
---------------------------
PVC is randomly allocated at start of the game and after discovery it is never reallocated

Desired functionality
----------------------
1. PVC is randomly allocated to a sector without a landmark and/or unit on it 
2. After discovery it is reallocated randomly to a sector without a landmark and/or unit on it
3. The player who last discovered the PVC will not trigger it even if he steps on him.

**Comment by Gorea235** [comment]
Since we are adding effects to the game, and sectors can have effects applied to them, it might be worth re-working the PVC to be a hidden effect that is applied to a sector by the game itself. That way, it can follow the standard trigger systems that other effects will also work with.

**Comment by Gorea235** [comment]
The PVC allocation system has been re-implemented, and it follows the old system we used. This means that it will be reallocated after the minigame finishes. The PVC is also now allocated to a sector via an effect that is applied, and when a sector is captured the trigger will save the current game state and trigger the scene switch.

Note: Since the scene switch only completes on the next update, it means that, until then, events are still processed. This means that if the player captured the PVC on their last action, the current turn can still switch. However, I will be added a static variable to the minigame manager class that is the ID of the player who captured the PVC, and it will use that, in conjunction with the minigame reward effect player ID property, to specify which player to give the reward to.

Since the minigame reward system needs some extra code to get the PVC allocation working 100%, I will leave this issue open until it is done.

**Comment by Gorea235** [comment]
The minigame has been modified to account for the new system, and the PVCEffect has been finalised to work with it. This means that the PVC allocation is now complete. Unless we need to tweak this further, this issue is now done.
