### ISSUE TITLE
Combat System rework

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#5]
Current implementation
---------------------------
"uncertainty" weighting doesn't behave as expected

Desired functionality
----------------------
The combat resolution should be consistently weighted so that the farther apart in strength the units are, the more certain it will be that the stronger unit will win. As a corollary, the closer the units are in terms of strength, the more random the outcome of the conflict will be.

**Comment by Nicodaw** [comment]
[Turns out the `Random.Range()` can be overloaded and the int version is exclusive](https://puu.sh/zwedT/fa9b93d6b1.png). Changing it to use `float` allows me to get into the other clauses, but unfortunately I have no idea if it works, because I can't understand what they were aiming at with writing to identical if and else clauses.

**Comment by Gorea235** [comment]
Huh, that's true. I'm not sure what the system is trying to accomplish really, I would have to have a few dry runs to see.

**Comment by Gorea235** [comment]
I forgot to mention that I worked out a function that would implement what the combat system is actually trying to do. It is a reverse-exponential function that decreases the probability of success the greater the different, without ever reaching 0. It can still be adjusted to improve gameplay, but it will work for now.

The function can be found [here](https://www.desmos.com/calculator/taaldm6iod).

**Comment by Gorea235** [comment]
We are now planning to overhaul much of the combat system. The current one feel a bit too unfair, both because the scaling of levels and attack/defence values allow for huge differences, and because the loser immediately dies.

The new rework will look to balance the combat by working with the level system. Losers in combat will have their level knocked down, and if it was low to begin with, they will be destroyed. This means that players won't feel like they've lost a large resource unfairly, and if the combat fails (which we need to decide if this is still a thing), the attacker doesn't just lose completely. It allow greater recovery from combat by both sides. This does mean that how we use the levels and attack/defence numbers in combat will require a rework, and it also means that we will have to utilise the card system to make units more flexible (e.g. provide cards that level up units, level down enemies, sacrifice units for personal gain, destroy enemy units (with negative to balance)), although I think it will be better for the game health in the long run.

**Comment by Gorea235** [comment]
Some updates on the combat rework: We are still planning to do it, however with slight adjustments. The level knock-down method seems to be the best way to do the combat at the moment, as it allows for similar attack/defence units to not be insta-destroyed, however we are planning to remove RNG completely, meaning that it will be entirely deterministic. This will likely mean that the values we use to knock-down units will be slightly lower, however it will make the game much more enjoyable to play.

**Comment by Nicodaw** [comment]
d80aef2952cdcc34fb686dba6d76938867cb6a7a finalised the transition from RNG to a stats based combat system
